"""Constants for Precision Plex read-only monitor."""

from homeassistant.const import CONF_ADDRESS

DOMAIN = "precision_plex"
PLATFORMS = ["binary_sensor", "cover", "button", "light", "switch", "number", "sensor"]

DEFAULT_TARGET_ADDRESS = "80:4B:50:D2:44:B4"
TARGET_SERVICE_UUID = "00726f62-6f74-7061-6a61-6d61732e6361"

PAIRING_CHARACTERISTIC_UUID = "01556963-6172-6173-6f6c-7574696f6e73"
PAIRING_INIT_PAYLOAD = bytes.fromhex("06")

STATE_CHARACTERISTIC_UUID = "02bb6f62-6f74-7061-6a61-6d61732e6361"

# Wireless TP monitor telemetry characteristic.
# Observed value handle 0x002B carries coach battery voltage in tenths of a volt.
BATTERY_CHARACTERISTIC_UUID = "02aa6f62-6f74-7061-6a61-6d61732e6361"

# Live monitor notification handles observed from Wireless TP traces.
COACH_BATTERY_NOTIFY_HANDLE = 0x002B

CONTROL_CHARACTERISTIC_UUID = "03726f62-6f74-7061-6a61-6d61732e6361"

from .profiles import DEFAULT_PROFILE, DEFAULT_PROFILE_ID, PROFILES, get_profile

COACH_PROFILE_ID = DEFAULT_PROFILE_ID
COACH_PROFILE = DEFAULT_PROFILE

STATE_BITS = COACH_PROFILE["state_bits"]
COMMAND_PAYLOADS = COACH_PROFILE["command_payloads"]

AWNING_LIGHT_TAP_SEQUENCE = COACH_PROFILE["awning_light_tap_sequence"]
WATER_PUMP_TAP = COACH_PROFILE["water_pump_tap"]
WATER_HEATER_TAP = COACH_PROFILE["water_heater_tap"]

# Compatibility exports for existing platform modules.
# These remain available so v4.1.0 does not change behavior or entity setup.
from .profiles.georgetown_gt5_34m5 import (  # noqa: E402,F401
    AWNING_IN_HOLD,
    AWNING_IN_RELEASE,
    AWNING_LIGHT_OFF,
    AWNING_LIGHT_ON,
    AWNING_LIGHT_PRESS,
    AWNING_LIGHT_RELEASE,
    AWNING_OUT_HOLD,
    AWNING_OUT_RELEASE,
    BED_SLIDE_IN_HOLD,
    BED_SLIDE_IN_RELEASE,
    BED_SLIDE_OUT_HOLD,
    BED_SLIDE_OUT_RELEASE,
    GENERATOR_AUTO_START_PRESS,
    GENERATOR_AUTO_START_SEQUENCE,
    GENERATOR_AUTO_STOP_PRESS,
    GENERATOR_AUTO_STOP_SEQUENCE,
    GENERATOR_RELEASE,
    GENERATOR_START_PRESS,
    GENERATOR_START_SEQUENCE,
    GENERATOR_STOP_PRESS,
    GENERATOR_STOP_SEQUENCE,
    SOFA_SLIDE_IN_HOLD,
    SOFA_SLIDE_IN_RELEASE,
    SOFA_SLIDE_OUT_HOLD,
    SOFA_SLIDE_OUT_RELEASE,
    WARDROBE_SLIDE_IN_HOLD,
    WARDROBE_SLIDE_IN_RELEASE,
    WARDROBE_SLIDE_OUT_HOLD,
    WARDROBE_SLIDE_OUT_RELEASE,
)
